# This file was automatically generated by Vpl
# utilization reports
report_utilization_impl true "mem_read2 mem_write1 increment mem_write3 mem_read1 mem_read3 mem_write2" "placed" "level0_i/ulp" $input_dir $vivado_output_dir
