# This file was automatically generated by Vpl
write_user_impl_clock_constraint "level0_i/ulp" "ulp_ucs/aclk_kernel_00 {is_user_set true instance ulp_ucs port aclk_kernel_00 clk_id 0 freq 160} ulp_ucs/aclk_kernel_01 {is_user_set false instance ulp_ucs port aclk_kernel_01 clk_id 1 freq 500.000000}" "" "output" "false"
